### ISSUE TITLE
How I can add classes that are not included in ScanNet200?

### ISSUE THREAD

**Issue by jeonhuhuhu** [ok-robot/ok-robot#10]
Could you please tell me 

if, in the framework of OK-Robot, when using the OWL-ViT model, which generates bounding boxes by comparing input images with labels from the ScanNet200 model, it is necessary to retrain the ScanNet200.

if I want to create new data labels for a specific environment, or should I simply add the desired specific labels to the CLASS_LABELS_200 list in the scannet_200_classes.py?

I am curious to know how I can add classes that are not included in ScanNet200.

**Comment by notmahi** [comment]
Yes, you have it right. You can add those new labels in this file: https://github.com/ok-robot/ok-robot/blob/main/ok-robot-navigation/voxel_map/dataloaders/scannet_200_classes.py

**Comment by emanuelazfernandes** [comment]
@jeonhuhuhu you can take a look in [ok-robot-navigation/voxel_map/dataloaders/record3d.py](https://github.com/ok-robot/ok-robot/blob/main/ok-robot-navigation/voxel_map/dataloaders/record3d.py) and compare it with [clip-fields/dataloaders/record3d.py](https://github.com/notmahi/clip-fields/blob/main/dataloaders/record3d.py) of which the authors did an adaptation, and implement/use the `custom_labels` method that they used there, in [Line 29](https://github.com/notmahi/clip-fields/blob/main/dataloaders/record3d.py#L29).
