### ISSUE TITLE
Can we test this project in home-robot env ?

### ISSUE THREAD

**Issue by yyy6812** [ok-robot/ok-robot#12]
Hi ,
I wonder how could we test this project in the home-robot virtual environment as we don't have the real robot yet.
Thank you for such a good open source work !

**Comment by notmahi** [comment]
We have not tested it, and since we are running all experiments in the real world, we don't plan to integrate it ourselves. However, if you would like to integrate it and may have a couple of questions on the way, let us know and we will do our best to help!
