### ISSUE TITLE
Do I have to use Python 3.9 when installing OK-Robot's environment? 

### ISSUE THREAD

**Issue by jeonhuhuhu** [ok-robot/ok-robot#15]
Do I have to use Python 3.9 when installing OK-Robot's environment? 

Could you please let me know what the problem is if I use Python 3.8? 

We are installing the environment with Python 3.9, but when we run stretch robot's "stretch_system_check.py", an error such as "ImportError: No module named apt_pkg" occurs. 

This problem is caused by a conflict with the existing installed Python 3.8. 

if there are no special problems with installation, is it okay to use Python 3.8?

**Comment by peiqi-liu** [comment]
We have not tried other python version, so if you find python 3.8 works, go for it. 
The only constraint is that AnyGrasp requires `3.9 >= python >= 3.6`.
However, I don't think you need to install any environment in Stretch Robot. The conda environment should be installed in another machine. The pipeline works in this way: you install `home-robot` on Stretch robot, and install conda environment on a machine that runs computationally heavy models such as AnyGrasp, LangSam etc.
Even though you insist installing environment in the robot, you should not run `stretch_system_check.py` in installed conda environment. You should run it in base environment.
