### ISSUE TITLE
Difference in Scannet200 labels

### ISSUE THREAD

**Issue by emanuelazfernandes** [ok-robot/ok-robot#16]
Thank you for the amazing work!

I noticed that there is a variation in the label dataset from the original Scannet200 and the ones presented in the paper.

Page 3, Section II.a.Detecting objects:
"[...] We supply a large set of such object queries, derived from the original Scannet200 labels [29] and presented in Appendix B, to help the detector captures most common objects in the scene."

Original: [BenchmarkScripts/ScanNet200/scannet200_constants.py](https://github.com/ScanNet/ScanNet/blob/master/BenchmarkScripts/ScanNet200/scannet200_constants.py#L57)
Used in this work: [ok-robot-navigation/voxel_map/dataloaders/scannet_200_classes.py](https://github.com/ok-robot/ok-robot/blob/main/ok-robot-navigation/voxel_map/dataloaders/scannet_200_classes.py#L4)

These have an intersection of 160 labels with the original and 48 extra added by the authors.

Could you elaborate on the reasoning behind the selection of the extra 48 labels and discarding of the other 40?

```python
EXTRA_48_CLASS_LABELS_200 = ['adapter', 'aerosol', 'alcohol disinfection', 'apple', 'banana', 'bascketball', 'baseball', 'beverage', 'body wash', 'can', 'charger', 'chopsticks', 'disinfecting wipes', 'face wash', 'fish oil', 'food', 'fruit', 'glass', 'hand sanitizer', 'hand sanitizers', 'hand wash', 'inhaler', 'marker pen', 'muffins', 'mug', 'multivitamin', 'mustard', 'notebook', 'package', 'paper towel', 'pepper', 'ping pong ball', 'plants', 'plastic bag', 'rag', 'salt', 'school bag', 'scissors', 'screwdriver', 'shower gel', 'soy sauce', 'spray', 'tape', 'tennis', 'toy', 'tripod', 'umbrella', 'water dispenser']
ORIGINAL_DISCARDED_40_CLASS_LABELS_200 = ['alarm clock', 'armchair', 'bar', 'bathroom counter', 'bathroom stall door', 'bench', 'blanket', 'board', 'ceiling', 'ceiling light', 'closet rod', 'closet wall', 'coffee table', 'copier', 'decoration', 'desk', 'dining table', 'end table', 'floor', 'folded chair', 'furniture', 'handicap bar', 'laundry basket', 'mat', 'mini fridge', 'office chair', 'rail', 'seat', 'shower curtain', 'shower curtain rod', 'shower door', 'shower floor', 'shower wall', 'sofa chair', 'stair rail', 'stand', 'toilet', 'tv stand', 'wall', 'wardrobe']
```
---
In the cited work [\[29\]](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/lib/constants/scannet_constants.py), the authors justify the selection of another subset of 200 from the original full Scannet 607 labels with "[...] from which we selected the 200-most represented categories by the number of instances, forming ScanNet200. The 200-class selection enables enforcing a minimum of 10 samples from all categories.".

Could a similar reasoning have happened here or was it empirical from the experiments in the real world?

**Comment by peiqi-liu** [comment]
The selection of labels is quite subjective based on our personal experience.

The purpose of these labels is simply to help OWL-ViT detect as many objects in images as possible. So as long as labels include a variety of objects, the detailed selection of labels should not be deterministic factor of system performance. That is to say if you find some other label set works well for you, you are encouraged to use it.
