### ISSUE TITLE
Errors while buiding environment

### ISSUE THREAD

**Issue by sun123-cmd** [ok-robot/ok-robot#2]
While installing graspAPI with `pip install graspnetAPI`,error occured as:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`
lang-sam 0.1.0 requires numpy<2.0.0,>=1.24.2, but you have numpy 1.20.3 which is incompatible.
supervision 0.18.0 requires numpy>=1.21.2, but you have numpy 1.20.3 which is incompatible.
How can I solve this problem?Thanks.

**Comment by yas777** [comment]
That error can be ignored as long as the numpy version is 1.20 and graspnetAPI is installed. You can proceed to the installation verification step and let us know if you are facing any issues.

**Comment by sun123-cmd** [comment]
> That error can be ignored as long as the numpy version is 1.20 and graspnetAPI is installed. You can proceed to the installation verification step and let us know if you are facing any issues.

Now I'm using numpy 1.20.3, however, `ImportError: cannot import name '__all__' from 'numpy.linalg' (/home/sun/miniconda3/envs/grasp-env/lib/python3.9/site-packages/numpy/linalg/__init__.py)`

**Comment by notmahi** [comment]
Could you try installing `numpy==1.23.0` and see if this works?

**Comment by sun123-cmd** [comment]
> Could you try installing `numpy==1.23.0` and see if this works?

Thanks, I have solved the problem in this way
