### ISSUE TITLE
Errors while buiding environment (MinkowskiEngine)

### ISSUE THREAD

**Issue by jeonhuhuhu** [ok-robot/ok-robot#6]
hi! 

I have re-implemented all of your CLIP-Field studies and successfully tested them. 

Now, we want to re-implement OK-Robot using Hello-Robot. 

An error occurred while installing the Mamba virtual environment, and we are trying to resolve it. 

The following problem occurred when installing `MinkowskiEngine`, and it was confirmed that if `MinkowskiEngine` was commented out, it was installed without a problem.

OS: Ubuntu 20.0 / GPU: RTX 3060 ti / CUDA: 11.8
`command: mamba env create -n ok-robot-env -f ./env-cu118.yml`

<img src="https://github.com/ok-robot/ok-robot/assets/148358798/a3b016d3-94b6-400b-ab58-6baae084fc87" width="80%">

<img src="https://github.com/ok-robot/ok-robot/assets/148358798/83d2a52e-5343-4113-b37e-080a555459e6" width="60%">

Did you install it without any problems?

Or will it be a problem if I comment out and install `grasping and graspnetAPI` and then install `grasping and graspnetAPI` separately?

However, aside from the issue with installing `MinkowskiEngine`, there were absolutely no problems with the installation process below.

<img src="https://github.com/ok-robot/ok-robot/assets/148358798/2cc2bc1c-a911-46d7-9077-b7c1a64ccb86" width="70%">

Thank you in advance for your help!

**Comment by notmahi** [comment]
Hard to debug this without knowing what the error is. 

In your mamba environment where everything is installed, could try to install MinkowskiEngine with pip, and copy-paste the entire output in your post?

**Comment by jeonhuhuhu** [comment]
> Hard to debug this without knowing what the error is.
> 
> In your mamba environment where everything is installed, could try to install MinkowskiEngine with pip, and copy-paste the entire output in your post?


I've resolved the issue! Thank you!!
