### ISSUE TITLE
issue of cfg file doesn't exists!.

### ISSUE THREAD

**Issue by jeonhuhuhu** [ok-robot/ok-robot#7]
Hi!

I'm facing the issue of `cfg file doesn't exists!`.

<img src="https://github.com/ok-robot/ok-robot/assets/148358798/e6d2e841-422a-4d87-99a1-ae1d179f509c" width="70%">

I have completed the anygrasp SDK license registration

<img src="https://github.com/ok-robot/ok-robot/assets/148358798/3b2a57f0-e524-434a-a9b7-de61e868f992" width="100%">

and have moved the registered license to the `anygrasp_license_registration/license` folder within OK-Robot, and I've confirmed it's copied there. 

However, I'm encountering an error stating that the `cfg file` is missing, and the only cfg file I have found is `licenseCfg.json` in the License folder. 

Should I be copying this to the `src` folder, or is there an issue with the license registration? 

Thank you in advance for your help.

**Comment by jeonhuhuhu** [comment]
> Hi!
> 
> I'm facing the issue of `cfg file doesn't exists!`.
> 
> <img alt="" width="70%" src="https://private-user-images.githubusercontent.com/148358798/313560547-e6d2e841-422a-4d87-99a1-ae1d179f509c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTM3MTYsIm5iZiI6MTcxMDgxMzQxNiwicGF0aCI6Ii8xNDgzNTg3OTgvMzEzNTYwNTQ3LWU2ZDJlODQxLTQyMmEtNGQ4Ny05OWExLWFlMWQxNzlmNTA5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTkyNzE5OTg5NGFjNzk4YjcxNTMwZjU5YmU3NjgzMzk5MGI5MDgzMjMwODdhMWY2MjhjZjVlNWUwZDQwNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NC0J3_9n8iM7tbvbqCJBDBP-sta6ICIn7ZDbxtZzA_c">
> I have completed the anygrasp SDK license registration
> 
> <img alt="" width="100%" src="https://private-user-images.githubusercontent.com/148358798/313560839-3b2a57f0-e524-434a-a9b7-de61e868f992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTM3MTYsIm5iZiI6MTcxMDgxMzQxNiwicGF0aCI6Ii8xNDgzNTg3OTgvMzEzNTYwODM5LTNiMmE1N2YwLWU1MjQtNDM0YS1hOWI3LWRlNjFlODY4Zjk5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzYzZDJkOTY2Zjk2Y2Q1NjI2MDViYzAyODMyYTRhMDc1ZDVjZWYwZTdjYzE5ZmRiZGIxNjdhM2VmNThlZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._7mQM4gW73QU7ZYI2xDUBkRjsBNN2Z6UehGr1B58ofs">
> and have moved the registered license to the `anygrasp_license_registration/license` folder within OK-Robot, and I've confirmed it's copied there.
> 
> However, I'm encountering an error stating that the `cfg file` is missing, and the only cfg file I have found is `licenseCfg.json` in the License folder.
> 
> Should I be copying this to the `src` folder, or is there an issue with the license registration?
> 
> Thank you in advance for your help.

We have resolved it.
Copying the authenticated license to path `/ok-robot-manipulation/src/` should resolve the issue.

**Comment by notmahi** [comment]
Sorry for the delayed response, but I am glad you figured this out!
