### ISSUE TITLE
Question for object in camera pose to object in base pose

### ISSUE THREAD

**Issue by nicehiro** [ok-robot/ok-robot#8]
Hi,

Thanks for your great work!

I'm working on implementing your work on other robots. I notice that you are calculating the theoretical transformation matrix of `object_in_camera` to `object_in_base`.

Is there a large error in the theoretical result? Did you do some external calibration?

**Comment by yas777** [comment]
Hi,

The initial gripper pose given by the model is relative to camera. But during manipulation as the camera frame moves we need a static frame of reference to get gripper pose relative to any moving frame [camera or gripper] during manipulation. That is the reason we are using base_link frame which is fixed at the initial base position when the robot is started.

**Comment by nicehiro** [comment]
I'm sorry for the unclear question. 

I know a fixed frame to do manipulation tasks is needed. And the transformation matrix of moving frame to fixed frame is calculated from the URDF, which are all theoretical values. 

But, in real-world experiments, the errors (for example, the camera position) may differ slightly from the URDF. How to handle it?

**Comment by notmahi** [comment]
The Stretch robots have a calibration method using which you can ensure your URDF model matches the real robot pretty closely. We need to run the calibration every once in a while, especially when we were moving the robot between homes, to ensure the hand-and-camera coordination is accurate.

Link to calibration doc: https://github.com/hello-robot/stretch_ros/tree/noetic/stretch_calibration which should show you how it is done on the robot.

Does this answer your question?

**Comment by nicehiro** [comment]
Yes. Thanks for your help.
